/**
 * Stable internal icon names mapped to lucide component names. Both lucide-react
 * (web) and lucide-react-native (native) export the same PascalCase names, so one
 * map drives both platforms.
 */
export const ICON_LUCIDE = {
  add: "Plus",
  drag: "GripVertical",
  chevronRight: "ChevronRight",
  chevronDown: "ChevronDown",
  page: "FileText",
  more: "MoreHorizontal",
  star: "Star",
  trash: "Trash2",
  rename: "Pencil",
  move: "CornerUpRight",
  folder: "Folder",
  comment: "MessageSquare",
  check: "Check",
  close: "X",
  send: "Send",
  text: "Type",
  h1: "Heading1",
  h2: "Heading2",
  h3: "Heading3",
  bulletList: "List",
  numberedList: "ListOrdered",
  checkList: "ListChecks",
  quote: "Quote",
  code: "Code",
  divider: "Minus",
  image: "Image",
  video: "Video",
  audio: "Music",
  file: "Paperclip",
  bookmark: "Bookmark",
  map: "MapPin",
  table: "Table",
  link: "Link",
  unlink: "Unlink",
  emoji: "Smile",
  search: "Search",
  lock: "Lock",
  unlock: "LockOpen",
  undo: "Undo2",
  redo: "Redo2",
  sun: "Sun",
  moon: "Moon",
  font: "CaseSensitive",
  cover: "ImagePlus",
  removeFormat: "RemoveFormatting",
  bold: "Bold",
  italic: "Italic",
  underline: "Underline",
  strike: "Strikethrough",
  pageLink: "FileSymlink",
  highlighter: "Highlighter",
  palette: "Palette",
  plus: "Plus",
  play: "Play",
  pause: "Pause",
  menu: "Menu",
} as const;

export type IconName = keyof typeof ICON_LUCIDE;
